### ISSUE TITLE
Will ntfs/vfat/exfat be supported?

### ISSUE THREAD

**Issue by chaoslawful** [cosmos72/fstransform#1]
Thank you for writing such a great tool! Is there roadmap for supporting ntfs/vfat/exfat?

**Comment by cosmos72** [comment]
I have good news :)

The NTFS kernel patch mentioned above has been accepted in recent Linux kernels (I tried 4.9.0, but anything newer than 2 years ago will probably do it).

So I wrote 'fsmount_kernel', a little program to mount a filesystem ignoring any FUSE driver, and patched the main 'fstransform' to use it.

I am currently testing the conversion from ntfs to ext4, stay tuned :)

**Comment by cosmos72** [comment]
Bingo! It works :)
