### ISSUE TITLE
ioctl('/mnt/sdf2/.fstransform.loop.10941', BLKGETSIZE64): Invalid argument

### ISSUE THREAD

**Issue by xulianh** [cosmos72/fstransform#27]
Trying to convert +3TB NTFS to EXT4. Initially the problem was `fsconvert ERROR: error opening loop-file '(null)': Bad address` trying to contnue a job that was interrupted by a system restart. 

Following the [guide](https://github.com/cosmos72/fstransform/issues/18#issuecomment-383393901) I got stuck at point 12. The error shown in console is:

> `sudo /usr/sbin/fsremap -n -q --resume-job=1 --cmd-umount=/bin/umount -- /mnt/sdf2/.fstransform.loop.10941 fsremap: resuming job 1, persistence data and logs are in '/var/tmp/fstransform/fsremap.job.1' ERROR: failed device fstat('/mnt/sdf2/.fstransform.loop.10941'), **re-run with option '-f' if you want to continue anyway (AT YOUR OWN RISK): Block device required**`

adding -f:

> `sudo /usr/sbin/fsremap -n -q -f --resume-job=1 --cmd-umount=/bin/umount -- /mnt/sdf2/.fstransform.loop.10941 fsremap: resuming job 1, persistence data and logs are in '/var/tmp/fstransform/fsremap.job.1' WARN: WARNING: failed device fstat('/mnt/sdf2/.fstransform.loop.10941'), continuing AT YOUR OWN RISK due to '-f': Block device required **ERROR: error in device ioctl('/mnt/sdf2/.fstransform.loop.10941', BLKGETSIZE64): Invalid argument**`

Following an unexpected system restart I had a restart and tried to continue from the point logs noted, but as the loop file wasn't given in the options it didn't run:

> `fsremap: you CAN RESUME it with: /usr/sbin/fsremap -n -q --resume-job=1 -- /dev/sdf2`
> `fsconvert ERROR: error opening loop-file '(null)': Bad address`

Any help please?

**Comment by cosmos72** [comment]
As I wrote in #18, the last argument of `fsremap --resume-job=N ...` must be the block device containing the file system, not the loop file inside it
