### ISSUE TITLE
fsremap crashes on large filesystems

### ISSUE THREAD

**Issue by ccantill** [cosmos72/fstransform#3]
I tried converting my 9.1TB JFS filesystem to EXT4 (so I could shrink it) and after three days of churning it finally got to the fsremap part which promptly crashed:

17:55:22 fstransform: mounting again device '/dev/md0' read-only
17:55:22 fstransform: launching '/usr/sbin/fsremap' in simulated mode
17:55:22 fsremap: starting job 1, persistence data and logs are in '/var/tmp/fstransform/fsremap.job.1'
17:55:22 fsremap: if this job is interrupted, for example by a power failure,
17:55:22 fsremap: you CAN RESUME it with: /usr/sbin/fsremap -n -q --resume-job=1 -- /dev/md0
17:55:23 fsremap: ERROR: ff_posix_fibmap(): error, dev_block_count = 7, file_block_count = 2441889920 overflow type (int): File too large
17:55:23 fsremap: ERROR: failed to list file blocks with ioctl(FS_IOC_FIEMAP): Operation not supported

**Comment by pthfdr-42** [comment]
@cosmos72 I think that there is a solution:
1. Create a smaller loop file, just enough to contain all files.
2. Remap the loop file to the beginning of the device, and zero out everything after the image's end.
(the FS size should be smaller than the underlying device size)
3. Ask the user to expand the FS to full device size.

    root:/u/h/root>touch TEST
    root:/u/h/root>truncate -s 10GiB TEST
    root:/u/h/root>mkfs.ext4 TEST
    mke2fs 1.45.0 (6-Mar-2019)
    Creating filesystem with 2621440 4k blocks and 655360 inodes
    Filesystem UUID: 79dfcfed-451b-41ad-97d8-570e8cfa87c3
    Superblock backups stored on blocks:
            32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632
    
    Allocating group tables: done
    Writing inode tables: done
    Creating journal (16384 blocks): done
    Writing superblocks and filesystem accounting information: done
    
    root:/u/h/root>mkdir TESTM
    root:/u/h/root>mount TEST TESTM
    root:/u/h/root>df TESTM/
    Filesystem     1K-blocks  Used Available Use% Mounted on
    /dev/loop0      10255636 36888   9678076   1% /usr/home/root/TESTM
    root:/u/h/root>umount TESTM
    root:/u/h/root>truncate -s 20GiB TEST
    root:/u/h/root>e2fsck -f TEST
    e2fsck 1.45.0 (6-Mar-2019)
    Pass 1: Checking inodes, blocks, and sizes
    Pass 2: Checking directory structure
    Pass 3: Checking directory connectivity
    Pass 4: Checking reference counts
    Pass 5: Checking group summary information
    TEST: 11/655360 files (0.0% non-contiguous), 66753/2621440 blocks
    root:/u/h/root>resize2fs TEST                                                                                                                                                                         
    resize2fs 1.45.0 (6-Mar-2019)
    Resizing the filesystem on TEST to 5242880 (4k) blocks.
    The filesystem on TEST is now 5242880 (4k) blocks long.
    
    root:/u/h/root>mount TEST TESTM
    root:/u/h/root>df TESTM
    Filesystem     1K-blocks  Used Available Use% Mounted on
    /dev/loop0      20576848 45036  19466852   1% /usr/home/root/TESTM
