### ISSUE TITLE
Does it make sense to use this project on partitions below 50% usage?

### ISSUE THREAD

**Issue by nlgranger** [cosmos72/fstransform#32]
Hi and thank you for this project.

When possible (partition occupation below 50%), would you rather recommend shrinking the source partition, adding a target one, moving the files and expanding the target afterward?
Which method do you reckon is the fastest/the safest?

**Comment by cosmos72** [comment]
Well, you can certainly use fstransform on partitions < 50% full.

But in such case you can also use many other techniques: what you suggest is certainly safer, and probably has similar speed (or even faster)

**Comment by nlgranger** [comment]
Ok, thank you for your feedback.
