### ISSUE TITLE
Is zfs supported in any way?

### ISSUE THREAD

**Issue by cworkschris** [cosmos72/fstransform#38]
It seems like for sure it is not officially supported, but some people seem to think it would work.

Can y'all explicitly clarify this?

Thanks for the awesome project - I hope to use it (I didn't realize before getting into zfs that it would be impossible to downsize!)

**Comment by cosmos72** [comment]
I have never tested converting zfs, so there **may** be unexpected issues - from relatively harmless, such as `fstransform` executing `fsck` with the wrong options, to serious ones such as corrupting the filesystem.

Having said that, it **may** work, but I would not risk my data on that

**Comment by chrisamow** [comment]
Fair enough!  Thanks for letting me know!

**Comment by cworkschris** [comment]
Fair enough!  Thanks for letting me know!
