### ISSUE TITLE
src/arch/mem_linux.cc:70: off by one error ?

### ISSUE THREAD

**Issue by dcb314** [cosmos72/fstransform#42]
static analyser cppcheck says:

mem_linux.cc:70:20: error: Width 256 given in format string (no. 1) is larger than destination buffer 'label[256]', use %255s to prevent overflowing it. [invalidScanfFormatWidth]

and

mem_linux.cc:70:20: error: Width 8 given in format string (no. 3) is larger than destination buffer 'unit[8]', use %7s to prevent overflowing it. [invalidScanfFormatWidth]

Source code is

        if ((err = fscanf(f, "%256s %" FT_ULL " %8s\n", label, & n_ull, unit)) <= 0) {

**Comment by cosmos72** [comment]
Thanks for spotting this! Fixed in commit ad5ceb6803781f6fb1aed556095120e35af816bb
