### ISSUE TITLE
GPL2-only → GPL2 or later

### ISSUE THREAD

**Issue by nckx** [cosmos72/fstransform#46]
Hi!

I'd love to package this project for [GNU Guix](https://guix.gnu.org), but hit a snag.

All of `fstransform` is free software but two files, [e4attr.cc](https://github.com/cosmos72/fstransform/blob/0.9.4/fsattr/src/e4attr.cc) and [e4attr.hh](https://github.com/cosmos72/fstransform/blob/0.9.4/fsattr/src/e4attr.cc), are released under a GPL2-only licence that would be incompatible with the majority of other code.

I don't *think* this currently causes legal problems, because code never happens to be combined in an incompatible way (*…yet*).

However, I'm not vouching for that either, and anyway this looks more like an oversight than a deliberate decision.

@cosmos72, would you be open to replacing the licence of GPL2-only files with one used elsewhere (such as [this GPL2-or-later one](https://github.com/cosmos72/fstransform/blob/master/fsattr/src/main.cc))?

**Comment by cosmos72** [comment]
Sure, I'll change the license to GPLv2+

**Comment by cosmos72** [comment]
done in commit b84684ced847fd0b7a8dbed222f84d2b27face17
