### ISSUE TITLE
Consider not using /bin/dash

### ISSUE THREAD

**Issue by maweki** [cosmos72/fstransform#7]
I am a Fedora user and dash is not usually part of a typical fedora install. If I am correct, only Ubuntu and its derivatives install these packages by default.

I've changed /bin/dash to /bin/bash before make install in the fstransform script and it seems to work for my case (transforming a xfs partition to ext4). I am still running the process (10% now) but so far no errors.

As far as I know, Ubuntu symlinks /bin/bash to /bin/dash for compatibility reasons so there should be no issue in changing that.

**Comment by maweki** [comment]
Yes, it worked for that case.

**Comment by cosmos72** [comment]
Hellp maweki,

yes, changing #!/bin/dash to #!/bin/bash in fstransform is expected to work.
To be honest, I am using #!/bin/dash simply to avoid the Debian package to depend on bash.
Actually, the "right" solution would be to rewrite fstransform in C++ - the heavy-lifting parts, fsremap and fsmove, have always been C++.

**Comment by maweki** [comment]
Since dash and bash should be fully compatible and /bin/bash is symlinked to /bin/bash, couldn't you, on debian packaging, leave the dash dependency but have /bin/bash in the sourcefile (or add a configure-statement)?

**Comment by cosmos72** [comment]
merged the pull request with your change dash -> bash

**Comment by cosmos72** [comment]
Since the script used dash, it **is** posix compliant without any bashism.

The point being discussed was that bash is more common than dash, so using #!/bin/dash was causing problems that could be solved by switching to a more common shell (bash, in this case)

**Comment by pthfdr-42** [comment]
Then use plain `/bin/sh`.
